accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'
urlpatterns = [
    path('', auth_views.LoginView.as_view(
        template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password-change/', auth_views.PasswordChangeView.as_view(
    template_name='accounts/password-change.html', success_url = '../logout'
    ), name='password-change'),
]

eastc/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('dashboard/', include(('dashboard.urls', 'dashboard'), namespace='dashboard')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
# class Role(models.Model):
#     role_name = models.CharField(max_length=20)
#     class Meta:
#         verbose_name_plural = "Role"
#     def __str__(self):
#         return self.role_name

class Profile(models.Model):
    PROGRAM_CHOICES = [
        ('BOS1','Bachelor\'s degree of official statistics first year'),
        ('BOS2','Bachelor\'s degree of official statistics second year'),
        ('lecturer','Lecturer'),
        ('administration','Admin')
    ]
    ROLE_CHOICES = [
        ('student', 'STUDENT'),
        ('coordinator', 'COORDINATOR'),
        ('supervisor', 'SUPERVISOR'),
        ('admin', 'ADMIN'),
    ]
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.PositiveIntegerField()
    program = models.CharField(max_length=20, choices=PROGRAM_CHOICES)
    role_name = models.CharField(max_length=100, choices=ROLE_CHOICES)
    count = models.PositiveIntegerField(default=1)
    class Meta:
        verbose_name_plural = "Profile"
    def __str__(self):
        full_name = self.user.first_name+" "+self.user.last_name
        return full_name+' - '+self.role_name


class UserAuthorization(models.Model):
    ROLE_CHOICES = [
        ('student', 'STUDENT'),
        ('coordinator', 'COORDINATOR'),
        ('supervisor', 'SUPERVISOR'),
        ('admin', 'ADMIN'),
    ]
    role_name = models.CharField(max_length=100, choices=ROLE_CHOICES)
    manage_users = models.BooleanField(default=False)
    submit_tasks = models.BooleanField(default=False)
    add_field_place = models.BooleanField(default=False)
    view_field_place = models.BooleanField(default=False)
    class Meta:
        verbose_name_plural = "User authorization"
    def __str__(self):
        return str(self.role)

accounts/views.py
from django.shortcuts import render
from django.contrib.auth import views as auth_views


# Create your views here.

# Here i wanted to define my own views but instead i used classbased inbuilt auth views

accounts/templates/accounts/account_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0 shrink-to-fit=no" />
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'w3-css.css' %}" />
    <link rel="stylesheet" href="{% static 'auth.css' %}" />
    <link rel="stylesheet" href="{% static 'fontawesome/css/font-awesome.min.css' %}">
    <title>EASTC PT | {% block title %}{% endblock %}</title>

  </head>
  <body class="auth_body">

    <div>
        {% block content %}{% endblock %}
    </div>

    <script type="text/javascript" src="{% static 'bootstrap/js/jquery.js'%}"></script>
    <script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>

    {% block blockjs %}{% endblock %}

  </body>
</html>

accounts/templates/accounts/login.html
{% extends './account_base.html' %} {% load static %}
{% load crispy_forms_tags %}
{% block title %}Login{% endblock %}
{% block content %}
<div class="outer_container">
  <div class="container">
    <div class="row">
      <div class="col-md-4 offset-md-4">
        <div class="w3-card w3-animate-zoom header">
          <p class="site-name">EASTC PT Login</p>
        </div>
        <div class="w3-card w3-animate-zoom login_content">
          <div class="login_image">
            <img src="{% static 'images/login.png' %}" alt="">
          </div>
          <div class="form_content">
            <form action="{% url 'accounts:login' %}" method="POST">
              {% csrf_token %}
              {{ form }}
              <div class="form-group">
                {% if request.GET.next %}
                <input type="hidden" name="next" value="{{ request.GET.next }}">
                {% endif %}
              </div>
              <button type="submit" class="btn">Login<i class="fa fa-sign-out"></i></button>
            </form>
          </div>
        </div>
        <div class="login_footer">
          <p>© EASTC field practical training {{current_date.year}}</p>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

accounts/templates/accounts/password-change.html
{% extends './account_base.html' %} {% load static %}
{% load crispy_forms_tags %}
{% block title %}Change-password{% endblock %}
{% block content %}
<div class="outer_container">
  <div class="container">
    <div class="row">
      <div class="col-md-6 offset-md-3">
        <div class="w3-card w3-animate-zoom login_content">
          <div class="form_content">
            <form class="form-group" action="{% url 'accounts:password-change'%}" method="post">
              {% csrf_token %}
              {{ form }}
              <button type="submit" class="btn">Confirm</button>
              </form>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}