dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='home'),
    path('tasks/', views.tasks_view, name='tasks'),
    path('field-schedule/', views.fieldSchedulePage, name='field-schedule'),
    path('arrival-notes/', views.arrival_view, name='arrival-notes'),
    path('add-field-place/', views.addfieldplace_view, name='add-field-place'),
    path('field-place-details/', views.fieldplacedetails_view, name='field-place-details'),
    path('manage-users/', views.manageusers_view, name='manage-users'),
]

eastc/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('dashboard/', include(('dashboard.urls', 'dashboard'), namespace='dashboard')),
]

dashboard/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class FieldSchedule(models.Model):
    study_year = models.CharField(max_length=20)
    weeks_number = models.PositiveIntegerField(default=0)
    from_date = models.DateField()
    to_date = models.DateField()
    created_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Field schedule'

    def __str__(self):
        return str(self.weeks_number)+"weeks "+str(self.from_date)+" "+str(self.to_date)

class Task(models.Model):
    """
    Field tasks model

    """
    week = models.PositiveIntegerField()
    const = models.PositiveIntegerField(default=1)
    day = models.CharField(max_length=50)
    task = models.TextField()
    lesson = models.TextField()
    hours = models.PositiveIntegerField()
    submission_date = models.DateTimeField(auto_now_add=True)
    student = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    created_date = models.DateField(auto_now_add=True)
    class Meta:
        verbose_name_plural = 'Tasks'
    def __str__(self):
        return str(self.student)+" - "+"week"+str(self.week)+" - "+self.day

class ArrivalNote(models.Model):
    pdf = models.FileField(upload_to='media/arrivalPDF/')
    student = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    created_date = models.DateField(auto_now_add=True)
    class Meta:
        verbose_name_plural = 'Arival notes'
    def __str__(self):
        return str(self.student)

class FieldPlace(models.Model):
    company_name = models.CharField(max_length=200)
    branch = models.CharField(max_length=100)
    department = models.CharField(max_length=200)
    region = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    supervisor_name = models.CharField(max_length=150)
    position = models.CharField(max_length=150)
    email = models.EmailField(max_length=254)
    student = models.ForeignKey(User, on_delete=models.CASCADE)
    created_date = models.DateField(auto_now_add=True)
    class Meta:
        verbose_name_plural = 'Field place'
    def __str__(self):
        return str(self.student) +" - "+ self.company_name

dashboard/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import *
from accounts.models import *

class FieldScheduleForm(forms.ModelForm):
    class Meta:
        model = FieldSchedule
        exclude = ['created_date']
        widgets = {
            'from_date': forms.DateInput(
            attrs = {
                'type':'date',
                'required':'true'
                }
            ),
            'to_date': forms.DateInput(
            attrs = {
                'type':'date',
                'required':'true'
                }
            ),
            'study_year': forms.TextInput(
            attrs = {
                'required':'true',
                'placeholder':'Example 2019/2020'
            }
            )
        }

class ArrivalUploadForm(forms.ModelForm):
    class Meta:
        model = ArrivalNote
        fields = ['pdf']
        widgets = {
            'pdf': forms.FileInput(
                attrs = {
                    'required':'true',
                    'class':'custom-file-input'
                }
            )
        }


class AddFieldPlaceForm(forms.ModelForm):
    class Meta:
        model = FieldPlace
        fields = ['company_name', 'branch',
                  'department', 'region',
                  'location', 'supervisor_name',
                  'position', 'email']

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['task','lesson','hours']
        widgets = {
            'task':forms.Textarea(
            attrs = {
                'cols':55,
                'rows':2
            }
            ),
            'lesson':forms.Textarea(
            attrs = {
                'cols':55,
                'rows':2
            }
            ),
        }



class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ['first_name', 'last_name','username', 'email', 'password1', 'password2']


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['program','phone','role_name']

dashboard/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Sum
from django.contrib.auth.models import User
from django.db.models import Sum
from .models import *
from accounts.models import *
from .forms import *
from datetime import datetime


# Create your views here.
current_date = datetime.now()

@login_required
def index(request):
    current_date = datetime.now()
    get_students = Profile.objects.filter(role_name = 'student')
    get_fieldplace_details = FieldPlace.objects.filter(created_date__year=current_date.year)
    get_current_studentsWith_fieldplacement = [i.student for i in get_fieldplace_details]
    get_submitted_arrivalNote = ArrivalNote.objects.filter(created_date__year=current_date.year)
    get_submitted_arrivalNoteUsers = [i.student for i in get_submitted_arrivalNote]
    totalBos1_submitted = 0
    totalBos2_submitted = 0
    for submitted_arrivalNote in get_submitted_arrivalNote:
        if submitted_arrivalNote.student.profile.program == 'BOS1':
            totalBos1_submitted += 1
        elif submitted_arrivalNote.student.profile.program == 'BOS2':
            totalBos2_submitted += 1
    get_users_totals = Profile.objects.all().values('program').annotate(Sum('count'))
    get_currentAvailablePrograms = [i['program'] for i in get_users_totals]
    get_tasks = Task.objects.filter(created_date__year=current_date.year).order_by('week')
    content = {
        'page_title': 'Dashboard',
        'get_students': get_students,
        'field_place_details':get_fieldplace_details,
        'current_studentsWith_fieldplacement':get_current_studentsWith_fieldplacement,
        'users_totals':get_users_totals,
        'programs':get_currentAvailablePrograms,
        'submitted_arrivalNote': get_submitted_arrivalNoteUsers,
        'totalBos1_submitted':totalBos1_submitted,
        'totalBos2_submitted':totalBos2_submitted,
        'task_data':get_tasks,
        }
    template_name = 'dashboard/index.html'
    return render(request,template_name,content)


@login_required
def tasks_view(request):
    current_date = datetime.now()
    get_currentScheduleWeeks = FieldSchedule.objects.get(from_date__year=current_date.year) if FieldSchedule.objects.filter(from_date__year=current_date.year).exists() else None
    get_weeks = [i+1 for i in range(int(get_currentScheduleWeeks.weeks_number))] if get_currentScheduleWeeks else None
    get_days  = ['Monday','Tuesday','Wednesday','Thursday','Friday']
    get_user_fromRequest = request.user
    get_user = User.objects.get(username=get_user_fromRequest)

    if request.method == 'POST':
        get_week = request.POST.get('week')
        get_day = request.POST.get('day')
        task_form = TaskForm(request.POST or None)
        if task_form.is_valid():
            instance = task_form.save(commit=False)
            instance.week = get_week[-1]
            instance.day = get_day
            instance.student = get_user
            instance.save()
            messages.success(request, f'Query Ok, Task and lesson learnt on {get_day.upper()} - {get_week.upper()} added succesifully')
            return redirect('dashboard:tasks')

    task_form = TaskForm()
    get_arrival_note = ArrivalNote.objects.get(student=get_user,created_date__year=current_date.year) if ArrivalNote.objects.filter(student=get_user,created_date__year=current_date.year).exists() else None
    get_tasks = list(Task.objects.filter(student=get_user, created_date__year=current_date.year).order_by('week'))

    get_totaltasksByweek= list(Task.objects.filter(student=get_user, created_date__year=current_date.year).values('week').annotate(Sum('const')))

    if get_weeks:
        for i in get_weeks:
            if i not in [task['week'] for task in get_totaltasksByweek]:
                dummy_count = {}
                dummy_count['week'] = i
                dummy_count['const__sum'] = 0
                get_totaltasksByweek.append(dummy_count)

    for task in get_totaltasksByweek:
        if task['const__sum'] < 5:
            get_daysByweek = Task.objects.filter(student=get_user,created_date__year=current_date.year,week=task['week']).values('day')
            get_daysByweek = [day['day'] for day in get_daysByweek]
            for day in get_days:
                dummy_task = {}
                dummy_task['week'] = task['week']
                if day not in get_daysByweek:
                    dummy_task['day'] = day
                    get_tasks.append(dummy_task)

    context = {
        'page_title': 'Field tasks',
        'form':task_form,
        'get_tasks':get_tasks,
        'arrival_note':get_arrival_note,
        'date':current_date,
        'scheduledWeeks':get_weeks,
        'days':get_days,
    }
    return render(request, 'dashboard/tasks.html', context)


@login_required
def arrival_view(request):
    current_date = datetime.now()
    get_currentScheduleWeeks = FieldSchedule.objects.get(from_date__year=current_date.year) if FieldSchedule.objects.filter(from_date__year=current_date.year).exists() else None
    if request.method == 'POST':
        form = ArrivalUploadForm(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.student = request.user
            instance.save()
            messages.success(request, f'You have succesifully uploaded your arrival note')
            return redirect('dashboard:arrival-notes')

    form = ArrivalUploadForm()
    get_user_arrivalUpload = ArrivalNote.objects.get(student=request.user,created_date__year=current_date.year) if ArrivalNote.objects.filter(student=request.user,created_date__year=current_date.year).exists() else None
    context = {
        'page_title': 'Arrival notes',
        'form': form,
        'date':current_date,
        'currentSchedule':get_currentScheduleWeeks,
        'user_arrived':get_user_arrivalUpload,
    }
    return render(request, 'dashboard/arrival-notes.html', context)


@login_required
def addfieldplace_view(request):
    if request.method == 'POST':
        form = AddFieldPlaceForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.student = request.user
            instance.save()
            return redirect('dashboard:add-field-place')

    student = request.user
    current_date = datetime.now()
    fieldplaceCheck = FieldPlace.objects.filter(student=student,created_date__year=current_date.year)
    form = AddFieldPlaceForm()
    context = {
        'page_title': 'Add field place',
        'form': form,
        'fieldplaceCheck':fieldplaceCheck,
    }
    return render(request, 'dashboard/add-field-place.html', context)


@login_required
def fieldplacedetails_view(request):
    current_date = datetime.now()
    student = request.user
    get_users = User.objects.all()
    fieldplaceCheck = FieldPlace.objects.filter(student=student,created_date__year=current_date.year)
    if fieldplaceCheck:
        fieldplace = FieldPlace.objects.get(student=student, created_date__year=current_date.year)
    else:
        fieldplace = None
    context = {
        'page_title': 'Field place details',
        'fieldplace': fieldplace,
        'users':get_users
    }
    return render(request, 'dashboard/field-place-details.html', context)

@login_required
def manageusers_view(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        profile_form = ProfileForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()
            messages.success(request, f'Query OK, user created succesifully')
            return redirect('dashboard:manage-users')
    user_form = UserRegistrationForm()
    profile_form = ProfileForm()
    get_users = User.objects.all().order_by("-id")
    page_title = "Manage users"
    template_name = 'dashboard/manageUsers.html'
    context = {
        'user_form':user_form,
        'profile_form':profile_form,
        'users':get_users,
        'page_title':page_title
    }
    return render(request, template_name, context)

@login_required
def fieldSchedulePage(request):
    current_date = datetime.now()
    get_all_fieldSchedules = FieldSchedule.objects.all()
    get_specificSchedule = FieldSchedule.objects.get(from_date__year=current_date.year) if FieldSchedule.objects.filter(from_date__year=current_date.year).exists() else None
    if request.method == 'POST' and "add_button" in request.POST:
        schedule_form = FieldScheduleForm(request.POST or None)
        academic_year = schedule_form.data['study_year']
        if schedule_form.is_valid():
            schedule_form.save()
            # messages.success(request, f'Query Ok, Field schedule for academic year {academic_year} added succesifully')
            return redirect('dashboard:field-schedule')
    if request.method == 'POST' and "edit_button" in request.POST:
        schedule_form = FieldScheduleForm(request.POST, instance=get_specificSchedule)
        academic_year = schedule_form.data['study_year']
        if schedule_form.is_valid():
            schedule_form.save()
            messages.success(request, f'Query OK, Field schedule for academic year {academic_year} updated succesifully')
            return redirect('dashboard:field-schedule')
    schedule_form = FieldScheduleForm()
    if get_specificSchedule:
        schedule_form = FieldScheduleForm(instance=get_specificSchedule)
    template_name = 'dashboard/fieldSchedule.html'
    context = {
        'page_title':"Field Schedule",
        'form':schedule_form,
        'date':current_date,
        'specificSchedule':get_specificSchedule,
        'all_fieldSchedules':get_all_fieldSchedules
    }
    return render(request, template_name, context)

dashboard/templates/dashboard/add-field-place.html
{% extends '../base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="add_field_place px-2">
  {% if get_currentScheduleWeeks %}
    {% if fieldplaceCheck %}
    <div class="exists_content" style="display:block;width:100%;">
      <div class="exists_message">
        <p>You have succesifully added your field place information click <strong><a href="{% url 'dashboard:field-place-details' %}"><i>here</i></a></strong>
        to view the details, or navigate to <strong><i>My place details</i></strong> on the dashboard sidebar.</p>

      </div>
    </div>
    {% else %}
    <form class="" action="{% url 'dashboard:add-field-place' %}" method="POST">
      {% csrf_token %}
      <div class="form-row">
        <div class="col-md-4">
          {{ form.company_name|as_crispy_field }}
        </div>
        <div class="col-md-4">
          {{ form.branch|as_crispy_field }}
        </div>
        <div class="col-md-4">
          {{ form.department|as_crispy_field }}
        </div>
      </div>
      <div class="form-row">
        <div class="col-md-6">
          {{ form.region|as_crispy_field }}
        </div>
        <div class="col-md-6">
          {{ form.location|as_crispy_field }}
        </div>
      </div>
      <div class="form-row">
        <div class="col-md-6">
          {{ form.supervisor_name|as_crispy_field }}
        </div>
        <div class="col-md-6">
          {{ form.position|as_crispy_field }}
        </div>
      </div>
      {{ form.email|as_crispy_field }}

      <button type="submit" value="submit" class="btn">Submit</button>
    </form>
    {% endif %}
  {% else %}
  <div class="exists_content" style="display:block;width:100%;">
    <div class="exists_message">
      <p>Field schedule for year <strong>{{current_date|date:"Y"}}</strong>
        has not yet been scheduled. you can not access this page's content
    </div>
  </div>
  {% endif %}
</div>
{% endblock %}

dashboard/templates/dashboard/arrival-notes.html
{% extends '../base.html' %}
{% load crispy_forms_tags %}
{% load humanize %}
{% block content %}
<div class="custom_file px-2">
  {% if currentSchedule %}
    {% if fieldplace %}
      {% if user_arrived %}
      <div class="exists_content">
        <div class="exists_message">
          <p><strong>{{ user.first_name|upper}} {{ user.last_name|upper}}</strong>, You have successifully uploaded your arrival note. You can now access task content</p>
        </div>
      </div>
      {% else %}
        <form action="{% url 'dashboard:arrival-notes' %}" method="POST" class="form-group" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="form-row">
            <div class=" col-md-10 custom-file">
              {{ form.pdf }}
              <label for="id_pdf" class="custom-file-label">Choose your file</label>
            </div>
            <div class="col-md-2">
              <button class="btn" type="submit" >Submit</button>
            </div>
          </div>
        </form>
      {% endif %}
    {% else %}
    <div class="exists_content" style="display:block;width:100%;">
      <div class="exists_message py-2 px-3">
        <h6 style="line-height:1.5em;"><strong>{{ user.first_name|upper }} {{ user.last_name|upper }}</strong>, You have not yet added your field place details. Add your field place details first to access this page's content.
          select <strong><a href="{% url 'dashboard:add-field-place' %}"><i>Add field place</i></a></strong> to fill the information</h6>
      </div>
    </div>
    {% endif %}
  {% else %}
  <div class="exists_content">
    <div class="exists_message">
      <p>Field schedule for year <strong>{{date|date:"Y"}}</strong>
        has not yet been scheduled. you can not access this page's content
    </div>
  </div>
  {% endif %}
</div>
{% endblock %}

dashboard/templates/dashboard/field-place-details.html
{% extends '../base.html' %}
{% load humanize %}
{% block content %}
<div class="fieldPlace_details pb-3">
  {% if get_currentScheduleWeeks %}
    {% if fieldplace %}
    <div class="col-md-12">
      <table class="table table-bordered table-striped">
        <tbody>
          <tr>
            <td width=30%>Company name</td>
            <td>{{ fieldplace.company_name.upper }}</td>
          </tr>
          <tr>
            <td>Branch</td>
            <td>{{ fieldplace.branch }}</td>
          </tr>
          <tr>
            <td>Department</td>
            <td>{{ fieldplace.department.upper }}</td>
          </tr>
          <tr>
            <td>Region</td>
            <td>{{ fieldplace.region }}</td>
          </tr>
          <tr>
            <td>Location</td>
            <td>{{ fieldplace.location }}</td>
          </tr>
          <tr>
            <td>Supervisor's name</td>
            <td>{{ fieldplace.supervisor_name.upper }}</td>
          </tr>
          <tr>
            <td>Position</td>
            <td>{{ fieldplace.position }}</td>
          </tr>
          <tr>
            <td>Email</td>
            <td>{{ fieldplace.email }}</td>
          </tr>
        </tbody>
      </table>
      <div class="table_footer">
        {% for user in users %}
        <div class="coordinator">
          {% if user.profile.role_name == "coordinator" %}
          <p><span>Name:</span> {{ user.first_name|upper}} {{ user.last_name|upper}}
            <br><span>Email:</span> {{ user.email }}
            <br><span>Phone number:</span> {{ user.phone }}
            <br><span>Role:</span> Eastc field coordinator</p>
            {% endif %}
        </div>
        {% endfor %}
      </div>
    </div>
    {% else %}
    <div class="exists_content" style="display:block;width:100%;">
      <div class="exists_message py-2 px-3">
        <h6 style="line-height:1.5em;"><strong>{{ user.first_name|upper }} {{ user.last_name|upper }}</strong>, You have not yet added your field place details. Add your field place details to view them here.
          select <strong><a href="{% url 'dashboard:add-field-place' %}"><i>Add field place</i></a></strong> to fill the information</h6>
      </div>
    </div>
    {% endif %}
  {% else %}
  <div class="exists_content" style="display:block;width:100%;">
    <div class="exists_message">
      <p>Field schedule for year <strong>{{current_date|date:"Y"}}</strong>
        has not yet been scheduled. you can not access this page's content
    </div>
  </div>
  {% endif %}
</div>
{% endblock %}

dashboard/templates/dashboard/fieldSchedule.html
{% extends '../base.html' %}
{% load humanize %}
{% block content %}
<div class="fieldschedule_container">
  <div class="row">
    <div class="col-md-12">
      {% if specificSchedule %}
      <div class="exists_content">
        <div class="exists_message">
          <p>Field schedule for year <strong>{{date|date:"Y"}}</strong> is added. Field attachment for academic year
            <strong>{{ specificSchedule.study_year }}</strong> is scheduled to start on
            <strong>{{ specificSchedule.from_date|date:"F d, Y" }}</strong> and ends on
            <strong>{{ specificSchedule.to_date|date:"F d, Y"}}</strong>. students are required to undertake
            <strong>{{specificSchedule.weeks_number}}</strong> weeks of Practical Training.
          </p>
        </div>
        <div class="fieldSchedule_data">
          <p>
            <button class="btn" type="button" data-toggle="collapse" data-target="#fieldScheduleEdit" aria-expanded="false" aria-controls="fieldScheduleEdit">
              Click to edit {{date|date:"Y"}} field schedule
            </button>
            <button class="btn" type="button" data-toggle="collapse" data-target="#fieldScheduleView" aria-expanded="false" aria-controls="fieldScheduleView">
              Click to view current and past field schedules
            </button>
          </p>
          <div class="collapse" id="fieldScheduleEdit">
            <div class="card card-body">
              <form class="" action="" method="post">
                {% csrf_token %}
                <div class="form-group">
                  {{ form }}
                </div>
                <div class="form-group">
                  <button type="submit" class="btn" name="edit_button">Edit</button>
                </div>
              </form>
            </div>
          </div>
          <div class="collapse" id="fieldScheduleView">
              <div class="table-responsive">
                <table class="table table-striped">
                  <thead>
                    <tr>
                      <th>S/no</th>
                      <th>Academic year</th>
                      <th>required no. of weeks</th>
                      <th>Start date</th>
                      <th>End date</th>
                      <th>Date created</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for fieldSchedule in all_fieldSchedules %}
                    <tr>
                      <th>{{forloop.counter}}</th>
                      <td>{{fieldSchedule.study_year}}</td>
                      <td>{{fieldSchedule.weeks_number}} weeks</td>
                      <td>{{fieldSchedule.from_date|date:"F d, Y"}}</td>
                      <td>{{fieldSchedule.to_date|date:"F d, Y"}}</td>
                      <td>{{fieldSchedule.created_date|date:"M d, Y g:ia"}}</td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
          </div>
        </div>
      </div>
      {% else %}
      <div class="form_content">
        <form class="" action="" method="post">
          {% csrf_token %}
          <div class="form-group">
            {{ form }}
          </div>
          <div class="form-group">
            <button type="submit" class="btn" name="add_button">Submit</button>
          </div>
        </form>
      </div>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

dashboard/templates/dashboard/manageUsers.html
{% extends '../base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="px-2">
  <div class="user_content">
    <div class="row">
      <div class="col-md-12">
        <form class="" action="" method="post">
          {% csrf_token %}
          <div class="form-row">
            <div class="col-md-4">
              {{ user_form.first_name|as_crispy_field }}
            </div>
            <div class="col-md-4">
              {{ user_form.last_name|as_crispy_field }}
            </div>
            <div class="col-md-4">
              {{ user_form.email|as_crispy_field }}
            </div>
          </div>
          <div class="form-row">
            <div class="col-md-6">
              {{ user_form.username|as_crispy_field }}
            </div>
            <div class="col-md-6">
              {{ profile_form.role_name|as_crispy_field }}
            </div>
          </div>
          <div class="form-row">
            <div class="col-md-6">
              {{ profile_form.program|as_crispy_field }}
            </div>
            <div class="col-md-6">
              {{ profile_form.phone|as_crispy_field }}
            </div>
          </div>
          <div class="form-row">
            <div class="col-md-6">
              {{ user_form.password1|as_crispy_field }}
            </div>
            <div class="col-md-6">
              {{ user_form.password2|as_crispy_field }}
            </div>
          </div>
          <div class="form-group">
            <button type="submit" class="btn" name="button">Add user</button>
          </div>
        </form>
      </div>
    </div>
  </div>
  <div class="view_users">
    <div class="accordion" id="viewUsersAccordion">
      <div class="accordion-item">
        <h2 class="accordion-header" id="headingOne">
          <button class="btn btn-block btn-outline-primary accordion-button" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            View users
          </button>
        </h2>
        <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne" data-parent="#viewUsersAccordion">
          <div class="accordion-body">
              <div class="table-responsive table_content">
                <table class="table table-bordered table-hover">
                  <caption>List of users</caption>
                  <thead class="

                  ">
                    <tr>
                      <th>S/No</th>
                      <th>Username</th>
                      <th>Full Name</th>
                      <th>Program</th>
                      <th>Email</th>
                      <th>Role</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for user in users %}
                    <tr>
                      <td>{{forloop.counter}}</td>
                      <td>{{ user.username }}</td>
                      <td>{{user.first_name}} {{user.last_name}}</td>
                      <td>{{user.profile.program}}</td>
                      <td>{{user.email}}</td>
                      <td>{{user.profile.role_name}}</td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
          </div>
        </div>
      </div>
    </div>
</div>
</div>
{% endblock %}