accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'
urlpatterns = [
    path('', auth_views.LoginView.as_view(
        template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password-change/', auth_views.PasswordChangeView.as_view(
    template_name='accounts/password-change.html', success_url = '../logout'
    ), name='password-change'),
]

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='home'),
    path('tasks/', views.tasks_view, name='tasks'),
    path('field-schedule/', views.fieldSchedulePage, name='field-schedule'),
    path('arrival-notes/', views.arrival_view, name='arrival-notes'),
    path('add-field-place/', views.addfieldplace_view, name='add-field-place'),
    path('field-place-details/', views.fieldplacedetails_view, name='field-place-details'),
    path('manage-users/', views.manageusers_view, name='manage-users'),
]

eastc/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('dashboard/', include(('dashboard.urls', 'dashboard'), namespace='dashboard')),
]

dashboard/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class FieldSchedule(models.Model):
    study_year = models.CharField(max_length=20)
    weeks_number = models.PositiveIntegerField(default=0)
    from_date = models.DateField()
    to_date = models.DateField()
    created_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Field schedule'

    def __str__(self):
        return str(self.weeks_number)+"weeks "+str(self.from_date)+" "+str(self.to_date)

class Task(models.Model):
    """
    Field tasks model

    """
    week = models.PositiveIntegerField()
    const = models.PositiveIntegerField(default=1)
    day = models.CharField(max_length=50)
    task = models.TextField()
    lesson = models.TextField()
    hours = models.PositiveIntegerField()
    submission_date = models.DateTimeField(auto_now_add=True)
    student = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    created_date = models.DateField(auto_now_add=True)
    class Meta:
        verbose_name_plural = 'Tasks'
    def __str__(self):
        return str(self.student)+" - "+"week"+str(self.week)+" - "+self.day

class ArrivalNote(models.Model):
    pdf = models.FileField(upload_to='media/arrivalPDF/')
    student = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    created_date = models.DateField(auto_now_add=True)
    class Meta:
        verbose_name_plural = 'Arival notes'
    def __str__(self):
        return str(self.student)

class FieldPlace(models.Model):
    company_name = models.CharField(max_length=200)
    branch = models.CharField(max_length=100)
    department = models.CharField(max_length=200)
    region = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    supervisor_name = models.CharField(max_length=150)
    position = models.CharField(max_length=150)
    email = models.EmailField(max_length=254)
    student = models.ForeignKey(User, on_delete=models.CASCADE)
    created_date = models.DateField(auto_now_add=True)
    class Meta:
        verbose_name_plural = 'Field place'
    def __str__(self):
        return str(self.student) +" - "+ self.company_name

dashboard/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import *
from accounts.models import *

class FieldScheduleForm(forms.ModelForm):
    class Meta:
        model = FieldSchedule
        exclude = ['created_date']
        widgets = {
            'from_date': forms.DateInput(
            attrs = {
                'type':'date',
                'required':'true'
                }
            ),
            'to_date': forms.DateInput(
            attrs = {
                'type':'date',
                'required':'true'
                }
            ),
            'study_year': forms.TextInput(
            attrs = {
                'required':'true',
                'placeholder':'Example 2019/2020'
            }
            )
        }

class ArrivalUploadForm(forms.ModelForm):
    class Meta:
        model = ArrivalNote
        fields = ['pdf']
        widgets = {
            'pdf': forms.FileInput(
                attrs = {
                    'required':'true',
                    'class':'custom-file-input'
                }
            )
        }


class AddFieldPlaceForm(forms.ModelForm):
    class Meta:
        model = FieldPlace
        fields = ['company_name', 'branch',
                  'department', 'region',
                  'location', 'supervisor_name',
                  'position', 'email']

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['task','lesson','hours']
        widgets = {
            'task':forms.Textarea(
            attrs = {
                'cols':55,
                'rows':2
            }
            ),
            'lesson':forms.Textarea(
            attrs = {
                'cols':55,
                'rows':2
            }
            ),
        }



class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ['first_name', 'last_name','username', 'email', 'password1', 'password2']


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['program','phone','role_name']

dashboard/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Sum
from django.contrib.auth.models import User
from django.db.models import Sum
from .models import *
from accounts.models import *
from .forms import *
from datetime import datetime


# Create your views here.
current_date = datetime.now()

@login_required
def index(request):
    current_date = datetime.now()
    get_students = Profile.objects.filter(role_name = 'student')
    get_fieldplace_details = FieldPlace.objects.filter(created_date__year=current_date.year)
    get_current_studentsWith_fieldplacement = [i.student for i in get_fieldplace_details]
    get_submitted_arrivalNote = ArrivalNote.objects.filter(created_date__year=current_date.year)
    get_submitted_arrivalNoteUsers = [i.student for i in get_submitted_arrivalNote]
    totalBos1_submitted = 0
    totalBos2_submitted = 0
    for submitted_arrivalNote in get_submitted_arrivalNote:
        if submitted_arrivalNote.student.profile.program == 'BOS1':
            totalBos1_submitted += 1
        elif submitted_arrivalNote.student.profile.program == 'BOS2':
            totalBos2_submitted += 1
    get_users_totals = Profile.objects.all().values('program').annotate(Sum('count'))
    get_currentAvailablePrograms = [i['program'] for i in get_users_totals]
    get_tasks = Task.objects.filter(created_date__year=current_date.year).order_by('week')
    content = {
        'page_title': 'Dashboard',
        'get_students': get_students,
        'field_place_details':get_fieldplace_details,
        'current_studentsWith_fieldplacement':get_current_studentsWith_fieldplacement,
        'users_totals':get_users_totals,
        'programs':get_currentAvailablePrograms,
        'submitted_arrivalNote': get_submitted_arrivalNoteUsers,
        'totalBos1_submitted':totalBos1_submitted,
        'totalBos2_submitted':totalBos2_submitted,
        'task_data':get_tasks,
        }
    template_name = 'dashboard/index.html'
    return render(request,template_name,content)


@login_required
def tasks_view(request):
    current_date = datetime.now()
    get_currentScheduleWeeks = FieldSchedule.objects.get(from_date__year=current_date.year) if FieldSchedule.objects.filter(from_date__year=current_date.year).exists() else None
    get_weeks = [i+1 for i in range(int(get_currentScheduleWeeks.weeks_number))] if get_currentScheduleWeeks else None
    get_days  = ['Monday','Tuesday','Wednesday','Thursday','Friday']
    get_user_fromRequest = request.user
    get_user = User.objects.get(username=get_user_fromRequest)

    if request.method == 'POST':
        get_week = request.POST.get('week')
        get_day = request.POST.get('day')
        task_form = TaskForm(request.POST or None)
        if task_form.is_valid():
            instance = task_form.save(commit=False)
            instance.week = get_week[-1]
            instance.day = get_day
            instance.student = get_user
            instance.save()
            messages.success(request, f'Query Ok, Task and lesson learnt on {get_day.upper()} - {get_week.upper()} added succesifully')
            return redirect('dashboard:tasks')

    task_form = TaskForm()
    get_arrival_note = ArrivalNote.objects.get(student=get_user,created_date__year=current_date.year) if ArrivalNote.objects.filter(student=get_user,created_date__year=current_date.year).exists() else None
    get_tasks = list(Task.objects.filter(student=get_user, created_date__year=current_date.year).order_by('week'))

    get_totaltasksByweek= list(Task.objects.filter(student=get_user, created_date__year=current_date.year).values('week').annotate(Sum('const')))

    if get_weeks:
        for i in get_weeks:
            if i not in [task['week'] for task in get_totaltasksByweek]:
                dummy_count = {}
                dummy_count['week'] = i
                dummy_count['const__sum'] = 0
                get_totaltasksByweek.append(dummy_count)

    for task in get_totaltasksByweek:
        if task['const__sum'] < 5:
            get_daysByweek = Task.objects.filter(student=get_user,created_date__year=current_date.year,week=task['week']).values('day')
            get_daysByweek = [day['day'] for day in get_daysByweek]
            for day in get_days:
                dummy_task = {}
                dummy_task['week'] = task['week']
                if day not in get_daysByweek:
                    dummy_task['day'] = day
                    get_tasks.append(dummy_task)

    context = {
        'page_title': 'Field tasks',
        'form':task_form,
        'get_tasks':get_tasks,
        'arrival_note':get_arrival_note,
        'date':current_date,
        'scheduledWeeks':get_weeks,
        'days':get_days,
    }
    return render(request, 'dashboard/tasks.html', context)


@login_required
def arrival_view(request):
    current_date = datetime.now()
    get_currentScheduleWeeks = FieldSchedule.objects.get(from_date__year=current_date.year) if FieldSchedule.objects.filter(from_date__year=current_date.year).exists() else None
    if request.method == 'POST':
        form = ArrivalUploadForm(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.student = request.user
            instance.save()
            messages.success(request, f'You have succesifully uploaded your arrival note')
            return redirect('dashboard:arrival-notes')

    form = ArrivalUploadForm()
    get_user_arrivalUpload = ArrivalNote.objects.get(student=request.user,created_date__year=current_date.year) if ArrivalNote.objects.filter(student=request.user,created_date__year=current_date.year).exists() else None
    context = {
        'page_title': 'Arrival notes',
        'form': form,
        'date':current_date,
        'currentSchedule':get_currentScheduleWeeks,
        'user_arrived':get_user_arrivalUpload,
    }
    return render(request, 'dashboard/arrival-notes.html', context)


@login_required
def addfieldplace_view(request):
    if request.method == 'POST':
        form = AddFieldPlaceForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.student = request.user
            instance.save()
            return redirect('dashboard:add-field-place')

    student = request.user
    current_date = datetime.now()
    fieldplaceCheck = FieldPlace.objects.filter(student=student,created_date__year=current_date.year)
    form = AddFieldPlaceForm()
    context = {
        'page_title': 'Add field place',
        'form': form,
        'fieldplaceCheck':fieldplaceCheck,
    }
    return render(request, 'dashboard/add-field-place.html', context)


@login_required
def fieldplacedetails_view(request):
    current_date = datetime.now()
    student = request.user
    get_users = User.objects.all()
    fieldplaceCheck = FieldPlace.objects.filter(student=student,created_date__year=current_date.year)
    if fieldplaceCheck:
        fieldplace = FieldPlace.objects.get(student=student, created_date__year=current_date.year)
    else:
        fieldplace = None
    context = {
        'page_title': 'Field place details',
        'fieldplace': fieldplace,
        'users':get_users
    }
    return render(request, 'dashboard/field-place-details.html', context)

@login_required
def manageusers_view(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        profile_form = ProfileForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()
            messages.success(request, f'Query OK, user created succesifully')
            return redirect('dashboard:manage-users')
    user_form = UserRegistrationForm()
    profile_form = ProfileForm()
    get_users = User.objects.all().order_by("-id")
    page_title = "Manage users"
    template_name = 'dashboard/manageUsers.html'
    context = {
        'user_form':user_form,
        'profile_form':profile_form,
        'users':get_users,
        'page_title':page_title
    }
    return render(request, template_name, context)

@login_required
def fieldSchedulePage(request):
    current_date = datetime.now()
    get_all_fieldSchedules = FieldSchedule.objects.all()
    get_specificSchedule = FieldSchedule.objects.get(from_date__year=current_date.year) if FieldSchedule.objects.filter(from_date__year=current_date.year).exists() else None
    if request.method == 'POST' and "add_button" in request.POST:
        schedule_form = FieldScheduleForm(request.POST or None)
        academic_year = schedule_form.data['study_year']
        if schedule_form.is_valid():
            schedule_form.save()
            # messages.success(request, f'Query Ok, Field schedule for academic year {academic_year} added succesifully')
            return redirect('dashboard:field-schedule')
    if request.method == 'POST' and "edit_button" in request.POST:
        schedule_form = FieldScheduleForm(request.POST, instance=get_specificSchedule)
        academic_year = schedule_form.data['study_year']
        if schedule_form.is_valid():
            schedule_form.save()
            messages.success(request, f'Query OK, Field schedule for academic year {academic_year} updated succesifully')
            return redirect('dashboard:field-schedule')
    schedule_form = FieldScheduleForm()
    if get_specificSchedule:
        schedule_form = FieldScheduleForm(instance=get_specificSchedule)
    template_name = 'dashboard/fieldSchedule.html'
    context = {
        'page_title':"Field Schedule",
        'form':schedule_form,
        'date':current_date,
        'specificSchedule':get_specificSchedule,
        'all_fieldSchedules':get_all_fieldSchedules
    }
    return render(request, template_name, context)

dashboard/templates/base.html
{% load static %}
{% url 'dashboard:home' as home %}
{% url 'dashboard:tasks' as tasks %}
{% url 'dashboard:arrival-notes' as arrival %}
{% url 'dashboard:add-field-place' as addplace%}
{% url 'dashboard:field-place-details' as fielddetails %}
{% url 'dashboard:manage-users' as manageUser %}
{% url 'dashboard:field-schedule' as fieldSchedule %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>EASTC PT | {{ page_title }}</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'w3-css.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}" />
    <link rel="stylesheet" href="{% static 'fontawesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/datatable.min.css' %}" />
    <!-- <script
      src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"
      charset="utf-8"
    ></script> -->
    <script src="{% static 'bootstrap/js/chart.js' %}"></script>
  </head>
  <body>

      <input type="checkbox" id="check" />
      <!--header area start-->
      <header class="w3-card">
        <label for="check">
          <i class="fa fa-bars" id="sidebar_btn"></i>
        </label>
        <div class="left_area">
          <h3>EASTC - <span>PT</span></h3>
        </div>
        <div class="right_area">
          <div class="d-flex">
            <div class="w3-dropdown-hover">
              <button class="w3-button">{{user.first_name}} {{user.last_name}}    <i class="fa fa-user"></i></button>
              <div class="w3-dropdown-content w3-bar-block w3-border w3-animate-zoom">
                <a href="{% url 'accounts:password-change' %}"  class="w3-bar-item w3-button"><img src="{% static 'images/changepassword.png'%}" alt="">Change-password</a>
                <a href="{% url 'accounts:logout' %}"  class="w3-bar-item w3-button"><img src="{% static 'images/logout.png'%}" alt="">Logout</a>
              </div>
            </div>
          </div>
        </div>
      </header>
      <!--header area end-->
      <!--mobile navigation bar start-->
      <div class="mobile_nav">
        <div class="nav_bar">
          <img
          src="{% static 'images/logo.gif' %}"
          class="mobile_profile_image"
          alt=""
          />
          <i class="fa fa-bars nav_btn"></i>
        </div>
        <div class="mobile_nav_items w3-animate-top">
          <a class="{% if request.path == home %}active{% endif %}" href="{% url 'dashboard:home' %}"
          ><i class="fa fa-desktop"></i><span>Dashboard</span></a
          >
          {% if user.profile.role_name == "student" %}
          <a class="{% if request.path == fielddetails %}active{% endif %}" href="{% url 'dashboard:field-place-details' %}"
          ><i class="fa fa-table"></i><span>My place details</span></a
          >
          <a class="{% if request.path == tasks %}active{% endif %}" href="{% url 'dashboard:tasks' %}"
          ><i class="fa fa-th"></i><span>Tasks</span></a
          >
          <a class="{% if request.path == arrival %}active{% endif %}" href="{% url 'dashboard:arrival-notes' %}"
          ><i class="fa fa-file"></i><span>Arrival notes</span></a
          >
          {% endif %}
          {% if user.profile.role_name == "admin" %}
          <a class="{% if request.path == manageUser %}active{% endif %}" href="{% url 'dashboard:manage-users' %}"
          ><i class="fa fa-file"></i><span>Manage users</span></a
          >
          {% endif %}
          {% if user.profile.role_name == "admin" or user.profile.role_name == "coordinator" %}
          <a class="{% if request.path == fieldSchedule %}active{% endif %}" href="{% url 'dashboard:field-schedule' %}"
          ><i class="fa fa-file"></i><span>Add Field Schedule</span></a
          >
          {% endif %}
          {% if user.profile.role_name == "student" %}
          <a href="{% url 'dashboard:add-field-place' %}"><i class="fa fa-cogs"></i><span>Add Field place</span></a>
          {% endif %}
          <a href="{% url 'dashboard:home' %}"><i class="fa fa-sliders-h"></i><span>Support</span></a>
        </div>
      </div>
      <!--mobile navigation bar end-->
      <!--sidebar start-->
      <div class="w3-card sidebar">
        <div class="profile_info">
          <img
          src="{% static 'images/logo.gif' %}"
          class="profile_image"
          alt=""
          />
        </div>
        <a class="{% if request.path == home %}active{% endif %}" href="{% url 'dashboard:home' %}"
        ><i class="fa fa-desktop"></i><span>Dashboard</span></a
        >
        {% if user.profile.role_name == "student" %}
        <a class="{% if request.path == fielddetails %}active{% endif %}" href="{% url 'dashboard:field-place-details' %}"
        ><i class="fa fa-table"></i><span>My place details</span></a
        >
        <a class="{% if request.path == tasks %}active{% endif %}" href="{% url 'dashboard:tasks' %}"
        ><i class="fa fa-th"></i><span>Tasks</span></a
        >
        <a class="{% if request.path == arrival %}active{% endif %}" href="{% url 'dashboard:arrival-notes' %}"
        ><i class="fa fa-file"></i><span>Arrival notes</span></a
        >
        {% endif %}
        {% if user.profile.role_name == "admin" %}
        <a class="{% if request.path == manageUser %}active{% endif %}" href="{% url 'dashboard:manage-users' %}"
        ><i class="fa fa-file"></i><span>Manage users</span></a
        >
        {% endif %}
        {% if user.profile.role_name == "admin" or user.profile.role_name == "coordinator" %}
        <a class="{% if request.path == fieldSchedule %}active{% endif %}" href="{% url 'dashboard:field-schedule' %}"
        ><i class="fa fa-file"></i><span>Add Field Schedule</span></a
        >
        {% endif %}
        {% if user.profile.role_name == "student" %}
        <a class="{% if request.path == addplace %}active{% endif %}" href="{% url 'dashboard:add-field-place' %}"><i class="fa fa-cogs"></i><span>Add Field place</span></a>
        {% endif %}
        <a href="{% url 'dashboard:home' %}"><i class="fa fa-question"></i><span>Support</span></a>
      </div>
      <!--sidebar end-->

      <!-- Content starts here -->
      <div class="content">
        <div class="page-title-box">
          <h4 class="page-title  w3-animate-zoom">
            Logged in as: {{ user.username }}
            <sub><span class="badge" style="padding:5px;"> {{user.profile.role_name|title}}, EASTC</span></sub>
          </h4>
          <div class="clearfix"></div>
        </div>

        <div class="card">
          <div class="boxpane-header">
            <h2 class="blue">
              <i class="fa fa-tachometer"></i>
              <span>{{ page_title }}</span>
            </h2>
          </div>
          <div class="row mt-2">
            <div class="col-md-4 col-sm-0"></div>
            <div class="col-md-8 col-sm-12">
              <div class="message w3-center">
                <div class="message_column">
                  {% if messages %}
                  {% for message in messages %}
                  <div class="alert alert-{{ message.tags }} alert-dismissible fade show w3-animate-top" role="alert">
                    {{message}}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  {% endfor %}
                  {% endif %}
                </div>
              </div>
            </div>
          </div>
          {% block content %} {% endblock %}
        </div>
      </div>
      <!-- content ends here -->
      <!-- footer starts here -->
      <div class="footer">
        {{current_date.year}} ©Eastern Africa Statistical Training Centre - Practical Training
        (EASTC-PT)
      </div>

    <script type="text/javascript" src="{% static 'bootstrap/js/jquery.js'%}"></script>
    <script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'bootstrap/js/pdfmake.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'bootstrap/js/vfs_fonts.js' %}"></script>
    <script type="text/javascript" src="{% static 'bootstrap/js/datatables.min.js' %}"></script>

    <script type="text/javascript">
      $(document).ready(function () {
        $(".nav_btn").click(function () {
          $(".mobile_nav_items").toggleClass("active");
        });
      });
    </script>
    {% block blockjs %}

    {% endblock %}
  </body>
</html>